import { useState } from 'react';
import { download, qs } from '../api';
import { DateFilters, dateParams, Empty, ErrorBox, fmtDate, fmtNum, PageHeader, Pager, Spinner, useApi } from '../ui';

/** Who booked what: per-employee totals, click a name to see every entry. */
export default function Activity() {
  const [d, setD] = useState({ preset: 'today', from: '', to: '' }); const f = dateParams(d); const { data, loading, error } = useApi('/activity' + qs(f)); const [user, setUser] = useState<any>(null); const [page, setPage] = useState(1);
  const det = useApi(user ? '/entries' + qs({ ...f, userId: user.userId, type: 'SALE', page, limit: 50 }) : null);
  return <><PageHeader title="Team activity" sub="What each sales employee booked">{user && <button className="btn" onClick={() => download('/reports/sales' + qs({ ...f, userId: user.userId, format: 'xlsx' }), `sales-${user.name}.xlsx`)}>Export {user.name}'s sales</button>}<button className="btn" onClick={() => download('/reports/sales' + qs({ ...f, format: 'xlsx' }), 'sales-all.xlsx')}>Export all sales</button></PageHeader>
    <div className="card p-3 mb-4 flex flex-wrap gap-2"><DateFilters v={d} set={(x: any) => { setD(x); setUser(null); }} /></div><ErrorBox msg={error} />
    <div className="card overflow-hidden mb-4">{loading && !data ? <Spinner /> : !data?.rows.length ? <Empty>No sales team users yet.</Empty> : <div className="overflow-x-auto"><table className="tbl"><thead><tr><th>Employee</th><th className="text-right">Lines booked</th><th className="text-right">Pieces booked</th><th></th></tr></thead>
      <tbody>{data.rows.map((r: any) => <tr key={String(r.userId)} className={user?.userId === r.userId ? 'bg-brand-soft' : ''}><td className="font-medium">{r.name}<span className="text-xs text-slate-500 ml-2">{r.username}</span></td><td className="text-right tabular-nums">{fmtNum(r.lines)}</td><td className="text-right tabular-nums font-semibold">{fmtNum(r.qty)}</td><td className="text-right">{r.lines > 0 ? <button className="btn !py-1" onClick={() => { setUser(r); setPage(1); }}>View entries</button> : <span className="text-xs text-slate-500">Nothing booked</span>}</td></tr>)}</tbody>
        <tfoot><tr><td className="px-3 py-2 font-semibold">Total</td><td className="px-3 py-2 text-right font-semibold">{fmtNum(data.totalLines)}</td><td className="px-3 py-2 text-right font-semibold">{fmtNum(data.totalQty)}</td><td /></tr></tfoot></table></div>}</div>
    {user && <div className="card overflow-hidden"><div className="px-4 py-3 font-semibold border-b border-slate-200">{user.name}: entries</div>{!det.data?.rows.length ? <Empty>No entries.</Empty> : <div className="overflow-x-auto"><table className="tbl"><thead><tr><th>Date</th><th>Item</th><th className="text-right">Qty</th><th>Customer</th><th>Status</th></tr></thead><tbody>{det.data.rows.map((r: any) => <tr key={r._id} className={r.cancelled ? 'opacity-50 line-through' : ''}><td className="whitespace-nowrap">{fmtDate(r.date)}</td><td className="font-medium">{r.itemId?.name}</td><td className="text-right tabular-nums">{fmtNum(Math.abs(r.quantity))}</td><td>{r.party || '—'}</td><td>{r.cancelled ? 'Cancelled' : ''}</td></tr>)}</tbody></table></div>}{det.data && <Pager page={det.data.page} pages={det.data.pages} total={det.data.total} onPage={setPage} />}</div>}</>;
}
