import { useState } from 'react';
import { Link } from 'react-router-dom';
import { api, download } from '../api';
import { useAuth } from '../App';
import { Empty, ErrorBox, Field, fmtDate, fmtNum, ItemPicker, PageHeader, Pager, Spinner, SupplierSelect, today, useApi, useToast } from '../ui';

type Tab = 'master' | 'qty' | 'invoice' | 'history';
export default function Import() {
  const { isAdmin } = useAuth(); const [tab, setTab] = useState<Tab>(isAdmin ? 'master' : 'invoice');
  const tabs: [Tab, string, boolean][] = [['master', 'Master data (Excel)', isAdmin], ['qty', 'Bulk stock quantity (Excel)', isAdmin], ['invoice', 'Invoice photo / PDF', true], ['history', 'Import history', isAdmin]];
  return <><PageHeader title="Import / Export" sub="Nothing is changed until you review the preview and confirm. Exports are on each page (Export Excel) and in Reports." />
    <div className="flex flex-wrap gap-1.5 mb-4 border-b border-slate-200 pb-3">{tabs.filter(t => t[2]).map(([k, l]) => <button key={k} onClick={() => setTab(k)} className={`rounded-md px-3.5 py-1.5 text-sm font-medium ${tab === k ? 'bg-brand text-white' : 'bg-white border border-slate-300 hover:bg-slate-100'}`}>{l}</button>)}</div>
    {tab === 'master' && <Wizard key="m" kind="MASTER" />}{tab === 'qty' && <Wizard key="q" kind="STOCK_QTY" />}{tab === 'invoice' && <Invoice />}{tab === 'history' && <History />}</>;
}

// ---------------------------------------------------------------- Excel wizard (master + bulk qty)
const MASTER_FIELDS: [string, string][] = [['name', 'Item name'], ['code', 'Item code'], ['supplier', 'Supplier'], ['currentStock', 'Current stock'], ['targetStock', 'Target / required stock'], ['reorderLevel', 'Reorder level'], ['reorderPct', 'Reorder %'], ['priority', 'Priority (yes/no)'], ['category', 'Category']];
const QTY_FIELDS: [string, string][] = [['name', 'Item name'], ['code', 'Item code (optional)'], ['currentStock', 'Quantity']];

function Wizard({ kind }: { kind: 'MASTER' | 'STOCK_QTY' }) {
  const toast = useToast(); const fields = kind === 'MASTER' ? MASTER_FIELDS : QTY_FIELDS;
  const [up, setUp] = useState<any>(null); const [sheet, setSheet] = useState(0); const [headerRow, setHeaderRow] = useState(0); const [mapping, setMapping] = useState<Record<string, number | null>>({});
  const [opts, setOpts] = useState<any>({ forcePriority: false, blankStockAsZero: true, useBoldCategories: true, mode: 'SET' }); const [plan, setPlan] = useState<any>(null); const [res, setRes] = useState<Record<number, any>>({});
  const [busy, setBusy] = useState(false); const [err, setErr] = useState(''); const [done, setDone] = useState<any>(null); const [view, setView] = useState('');
  const reset = () => { setUp(null); setPlan(null); setDone(null); setRes({}); setErr(''); };
  async function upload(file: File) {
    setBusy(true); setErr(''); try { const fd = new FormData(); fd.append('file', file); fd.append('kind', kind); const d = await api.upload('/import/upload', fd); setUp(d); pickSheet(d, 0); } catch (e: any) { setErr(e.message); } finally { setBusy(false); }
  }
  function pickSheet(d: any, i: number) { setSheet(i); setHeaderRow(d.sheets[i].headerRow); setMapping(d.sheets[i].suggestedMapping); setPlan(null); setRes({}); }
  const body = (r = res) => ({ sheet, headerRow, mapping, options: kind === 'MASTER' ? { forcePriority: opts.forcePriority || null, blankStockAsZero: opts.blankStockAsZero, useBoldCategories: opts.useBoldCategories } : { mode: opts.mode }, resolutions: r });
  async function preview(r = res) { setBusy(true); setErr(''); try { const d = await api.post(`/import/${up.importId}/preview`, body(r)); setPlan(d.plan); setView(v => v || (kind === 'MASTER' ? (d.plan.summary.unresolved ? 'review' : 'new') : 'matched')); } catch (e: any) { setErr(e.message); } finally { setBusy(false); } }
  const resolve = (row: number, v: any) => { const r = { ...res }; if (v) r[row] = v; else delete r[row]; setRes(r); preview(r); };
  async function commit() {
    const s = plan.summary; const msg = kind === 'MASTER' ? `Import now?\n\n• ${s.willCreate} new items will be created\n• ${s.willUpdate} existing items will be updated\n• ${s.willSkip} rows will be skipped` : `Apply stock update to ${plan.summary.willApply} items?\n\nUnmatched, duplicate and invalid rows will NOT be applied.`;
    if (!confirm(msg)) return; setBusy(true); setErr(''); try { const d = await api.post(`/import/${up.importId}/commit`, { ...body(), confirm: true }); setDone(d); toast(`Import complete`); } catch (e: any) { setErr(e.message); } finally { setBusy(false); }
  }
  if (done) return <div className="card p-6 max-w-xl space-y-3"><h2 className="text-lg font-semibold text-ok">Import complete</h2><p className="text-sm">Created <b>{done.counts.created}</b>, updated <b>{done.counts.updated}</b>, skipped <b>{done.counts.skipped}</b>, failed <b>{done.counts.failed}</b>. If something looks wrong you can undo it under <i>Import history</i>.</p><div className="flex gap-2"><Link className="btn btn-primary" to="/items">View items</Link><button className="btn" onClick={reset}>Import another file</button></div></div>;
  if (!up) return <div className="card p-5 max-w-2xl space-y-3"><h2 className="font-semibold">{kind === 'MASTER' ? 'Step 1: choose your Excel file' : 'Step 1: choose a file with item name (or code) and quantity'}</h2>
    <p className="text-sm text-slate-600">{kind === 'MASTER' ? 'Works with .xlsx, .xls and .csv. The first file should be your priority list (tick “Mark every row as top priority” in the next step), then your stock list. Items already in the system are updated, never duplicated.' : 'Each row sets (or adds to) the stock of the matching item. You will see matched, unmatched, duplicate and invalid rows before anything changes.'}</p><ErrorBox msg={err} />
    <input className="inp" type="file" accept=".xlsx,.xls,.csv" disabled={busy} onChange={e => e.target.files?.[0] && upload(e.target.files[0])} />{busy && <Spinner />}</div>;
  const sh = up.sheets[sheet];
  return <div className="space-y-4"><div className="card p-4 space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">Step 2: match columns — {up.fileName}</h2><button className="btn" onClick={reset}>Choose another file</button></div><ErrorBox msg={err} />
    <div className="grid gap-3 sm:grid-cols-3"><Field label="Sheet"><select className="inp" value={sheet} onChange={e => pickSheet(up, Number(e.target.value))}>{up.sheets.map((s: any, i: number) => <option key={i} value={i}>{s.name} ({s.rowCount} rows)</option>)}</select></Field>
      <Field label="Header row number" hint="Row that contains the column titles"><input className="inp" type="number" min={1} value={headerRow + 1} onChange={e => { const n = Math.max(0, Number(e.target.value) - 1); setHeaderRow(n); setPlan(null); }} /></Field></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{fields.map(([k, label]) => <Field key={k} label={label}><select className="inp" value={mapping[k] ?? ''} onChange={e => { setMapping({ ...mapping, [k]: e.target.value === '' ? null : Number(e.target.value) }); setPlan(null); }}><option value="">— not in file —</option>{sh.header.map((h: string, i: number) => <option key={i} value={i}>{h || `(column ${i + 1})`}</option>)}</select></Field>)}</div>
    {kind === 'MASTER' ? <div className="space-y-1.5 text-sm"><label className="flex gap-2"><input type="checkbox" checked={opts.forcePriority} onChange={e => { setOpts({ ...opts, forcePriority: e.target.checked }); setPlan(null); }} />Mark every row in this file as <b>top priority</b> (use for your priority list)</label>
      <label className="flex gap-2"><input type="checkbox" checked={opts.blankStockAsZero} onChange={e => { setOpts({ ...opts, blankStockAsZero: e.target.checked }); setPlan(null); }} />Treat a blank stock cell as 0 (only applies if a stock column is selected)</label>
      <label className="flex gap-2"><input type="checkbox" checked={opts.useBoldCategories} onChange={e => { setOpts({ ...opts, useBoldCategories: e.target.checked }); setPlan(null); }} />Bold rows with no numbers are category headings, not items</label></div>
      : <Field label="How should quantities be applied?"><select className="inp max-w-sm" value={opts.mode} onChange={e => { setOpts({ ...opts, mode: e.target.value }); setPlan(null); }}><option value="SET">Set stock to this quantity (counted stock)</option><option value="ADD">Add this quantity to current stock</option></select></Field>}
    <details className="text-sm"><summary className="cursor-pointer text-slate-600">Show first rows of the sheet</summary><div className="overflow-x-auto mt-2"><table className="tbl"><thead><tr>{sh.header.map((h: string, i: number) => <th key={i}>{h || `(col ${i + 1})`}</th>)}</tr></thead><tbody>{sh.sample.map((r: any[], i: number) => <tr key={i}>{sh.header.map((_: any, j: number) => <td key={j}>{String(r[j] ?? '')}</td>)}</tr>)}</tbody></table></div></details>
    <button className="btn btn-primary" disabled={busy || (mapping.name == null && mapping.code == null)} onClick={() => preview()}>{busy ? 'Reading…' : 'Preview import'}</button></div>
    {plan && (kind === 'MASTER' ? <MasterPreview plan={plan} view={view} setView={setView} res={res} resolve={resolve} busy={busy} commit={commit} /> : <QtyPreview plan={plan} view={view} setView={setView} resolve={resolve} busy={busy} commit={commit} />)}</div>;
}

function Card({ n, label, tone, active, onClick }: { n: number; label: string; tone?: string; active?: boolean; onClick?: () => void }) {
  return <button onClick={onClick} className={`card p-3 text-left border-l-4 ${tone || 'border-slate-300'} ${active ? 'ring-2 ring-brand' : ''} ${onClick ? 'hover:bg-slate-50' : ''}`}><div className="text-xl font-semibold tabular-nums">{fmtNum(n)}</div><div className="text-xs text-slate-600">{label}</div></button>;
}
const SHOW = 200;
function MasterPreview({ plan, view, setView, res, resolve, busy, commit }: any) {
  const s = plan.summary; const all: any[] = plan.rows;
  const views: Record<string, [string, (r: any) => boolean, number, string]> = {
    review: ['Needs your decision', r => r.action === 'REVIEW', s.unresolved, 'border-bad'], new: ['New items', r => r.action === 'CREATE', s.newItems, 'border-ok'], existing: ['Existing items', r => r.action === 'UPDATE', s.existingItems, 'border-brand'],
    dups: ['Duplicates in file', r => r.kind === 'DUP_IN_FILE', s.duplicatesInFile, 'border-warn'], similar: ['Similar names (check)', r => r.action === 'CREATE' && r.suggestions.length > 0, all.filter((r: any) => r.action === 'CREATE' && r.suggestions.length).length, 'border-warn'],
    crit: ['Criteria missing', r => r.flags.includes('MISSING_CRITERIA'), s.missingCriteria, 'border-unset'], sup: ['Supplier missing', r => r.flags.includes('MISSING_SUPPLIER'), s.missingSupplier, 'border-unset'], bad: ['Invalid rows', r => r.kind === 'INVALID', s.invalidRows, 'border-dead'], cats: ['Category headings', r => r.kind === 'CATEGORY', s.categoryHeaders, 'border-slate-300'] };
  const rows = all.filter(views[view]?.[1] || (() => true)); const decisions = (r: any) => <select className="inp !py-1" value={res[r.rowNum]?.action === 'LINK' ? 'L:' + res[r.rowNum].itemId : res[r.rowNum]?.action || ''} onChange={e => { const v = e.target.value; resolve(r.rowNum, !v ? null : v.startsWith('L:') ? { action: 'LINK', itemId: v.slice(2) } : { action: v }); }}>
    <option value="">{r.action === 'REVIEW' ? 'Choose…' : 'Create as new item'}</option>{r.action === 'REVIEW' && <option value="CREATE">Create as new item</option>}<option value="SKIP">Skip this row</option>{r.suggestions.map((c: any) => <option key={c.id} value={'L:' + c.id}>Same as: {c.name}</option>)}</select>;
  return <div className="space-y-3"><div className="card p-4"><h2 className="font-semibold mb-3">Step 3: preview — nothing has been changed yet</h2>
    <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 xl:grid-cols-9 gap-2">{Object.entries(views).map(([k, [label, , n, tone]]) => <Card key={k} n={n} label={label} tone={tone} active={view === k} onClick={() => setView(k)} />)}</div>
    {s.unresolved > 0 && <p className="mt-3 text-sm text-bad">{s.unresolved} row(s) look like duplicates of another item. Decide for each one under “Needs your decision”, then you can import.</p>}</div>
    <div className="card overflow-hidden"><div className="px-4 py-2 border-b border-slate-200 text-sm font-semibold">{views[view]?.[0]} {rows.length > SHOW && <span className="font-normal text-slate-500">(showing first {SHOW} of {rows.length})</span>}</div>
      {!rows.length ? <Empty>Nothing here.</Empty> : <div className="overflow-x-auto max-h-[28rem]"><table className="tbl"><thead><tr><th>Row</th><th>Item name</th><th className="text-right">Stock</th><th className="text-right">Target</th><th>Supplier</th><th>Result</th><th>Decision</th></tr></thead>
        <tbody>{rows.slice(0, SHOW).map((r: any) => <tr key={r.rowNum}><td>{r.rowNum}</td><td className="font-medium">{r.values.name}{r.values.category && <div className="text-xs text-slate-500">{r.values.category}</div>}</td><td className="text-right">{fmtNum(r.values.currentStock)}</td><td className="text-right">{fmtNum(r.values.targetStock)}</td><td>{r.values.supplierName || '—'}</td>
          <td className="text-xs">{r.errors.length ? <span className="text-bad">{r.errors.join('; ')}</span> : r.kind === 'EXISTING' ? <>Updates “{r.matchItemName}”</> : r.kind === 'DUP_IN_FILE' ? <>Same as row {r.sameAsRow}, skipped</> : r.kind === 'POSSIBLE_DUP' ? <span className="text-bad">{r.sameAsRow ? `Looks like row ${r.sameAsRow}` : `Looks like an existing item`}</span> : r.kind === 'CATEGORY' ? 'Category heading' : 'New item'}{r.flags.filter((f: string) => !['DUPLICATE_IN_FILE'].includes(f)).map((f: string) => <span key={f} className="ml-1 rounded bg-slate-100 px-1">{f.replace(/_/g, ' ').toLowerCase()}</span>)}</td>
          <td className="min-w-[14rem]">{r.kind === 'POSSIBLE_DUP' || (r.action === 'CREATE' && r.suggestions.length) || res[r.rowNum] ? (r.sameAsRow && r.kind === 'POSSIBLE_DUP' ? <select className="inp !py-1" value={res[r.rowNum]?.action || ''} onChange={e => resolve(r.rowNum, e.target.value ? { action: e.target.value } : null)}><option value="">Choose…</option><option value="CREATE">Keep both</option><option value="SKIP">Skip this row</option></select> : decisions(r)) : null}</td></tr>)}</tbody></table></div>}</div>
    <div className="card p-4 flex flex-wrap items-center justify-between gap-3"><div className="text-sm"><b>{s.willCreate}</b> new · <b>{s.willUpdate}</b> updated · <b>{s.willSkip}</b> skipped · <b>{s.invalidRows}</b> invalid</div><button className="btn btn-primary" disabled={busy || s.unresolved > 0 || s.willCreate + s.willUpdate === 0} onClick={commit}>Confirm import</button></div></div>;
}
function QtyPreview({ plan, view, setView, resolve, busy, commit }: any) {
  const s = plan.summary; const rows = plan.rows.filter((r: any) => r.bucket === (({ matched: 'MATCHED', unmatched: 'UNMATCHED', dups: 'DUPLICATE', invalid: 'INVALID', unchanged: 'UNCHANGED' } as any)[view] || 'MATCHED'));
  const cards: [string, string, number, string][] = [['matched', 'Matched', s.matched, 'border-ok'], ['unmatched', 'Unmatched', s.unmatched, 'border-bad'], ['dups', 'Duplicates', s.duplicates, 'border-warn'], ['invalid', 'Invalid', s.invalid, 'border-dead'], ['unchanged', 'No change', s.unchanged, 'border-slate-300']];
  return <div className="space-y-3"><div className="card p-4"><h2 className="font-semibold mb-3">Step 3: preview — nothing has been changed yet</h2><div className="grid grid-cols-2 sm:grid-cols-5 gap-2">{cards.map(([k, l, n, t]) => <Card key={k} n={n} label={l} tone={t} active={view === k} onClick={() => setView(k)} />)}</div></div>
    <div className="card overflow-hidden">{!rows.length ? <Empty>Nothing here.</Empty> : <div className="overflow-x-auto max-h-[28rem]"><table className="tbl"><thead><tr><th>Row</th><th>In file</th><th className="text-right">Qty</th><th>Matched item</th><th className="text-right">Current</th><th className="text-right">New stock</th><th>Notes</th></tr></thead>
      <tbody>{rows.slice(0, SHOW).map((r: any) => <tr key={r.rowNum}><td>{r.rowNum}</td><td className="font-medium">{r.name || r.code}</td><td className="text-right">{fmtNum(r.qty)}</td><td>{r.itemName || '—'}</td><td className="text-right">{fmtNum(r.currentStock)}</td><td className="text-right font-semibold">{fmtNum(r.newStock)}</td>
        <td className="text-xs min-w-[14rem]">{r.error && <span className="text-bad">{r.error}</span>}{r.bucket === 'UNMATCHED' && <div className="space-y-1">{r.suggestions.length > 0 && <select className="inp !py-1" defaultValue="" onChange={e => e.target.value && resolve(r.rowNum, { action: 'LINK', itemId: e.target.value })}><option value="">Did you mean…</option>{r.suggestions.map((c: any) => <option key={c.id} value={c.id}>{c.name}</option>)}</select>}<ItemPicker value={null} onPick={i => i && resolve(r.rowNum, { action: 'LINK', itemId: i.id })} placeholder="Search item to link…" /></div>}{r.bucket === 'DUPLICATE' && <button className="btn !py-1" onClick={() => resolve(r.rowNum, { action: 'USE' })}>Use this row</button>}</td></tr>)}</tbody></table></div>}</div>
    <div className="card p-4 flex flex-wrap items-center justify-between gap-3"><div className="text-sm"><b>{s.willApply}</b> items will be updated. Unmatched, duplicate and invalid rows are left alone.</div><button className="btn btn-primary" disabled={busy || s.willApply === 0} onClick={commit}>Confirm import</button></div></div>;
}

// ---------------------------------------------------------------- Invoice OCR
interface Line { key: number; rawName: string; quantity: string; status: string; itemId?: string; itemName?: string; candidates: any[] }
function Invoice() {
  const toast = useToast(); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [err, setErr] = useState(''); const [ocrErr, setOcrErr] = useState('');
  const [invoiceId, setInvoiceId] = useState(''); const [lines, setLines] = useState<Line[] | null>(null); const [supplierId, setSup] = useState(''); const [date, setDate] = useState(today()); const [invNo, setInvNo] = useState(''); const [done, setDone] = useState<any>(null);
  const mk = (rows: any[]): Line[] => rows.map((r, i) => ({ key: i, rawName: r.rawName, quantity: r.quantity == null ? '' : String(r.quantity), status: r.status, itemId: r.itemId, itemName: r.itemName, candidates: r.candidates || [] }));
  async function extract() { if (!file) return; setBusy(true); setErr(''); setOcrErr(''); try { const fd = new FormData(); fd.append('file', file); const d = await api.upload('/import/invoice', fd); setInvoiceId(d.invoiceId); setLines(mk(d.rows)); setOcrErr(d.ocrError || ''); } catch (e: any) { setErr(e.message); } finally { setBusy(false); } }
  const upd = (k: number, p: Partial<Line>) => setLines(l => l!.map(x => (x.key === k ? { ...x, ...p } : x)));
  const link = (k: number, i: any) => upd(k, i ? { itemId: i.id, itemName: i.name, status: 'MATCHED' } : { itemId: undefined, itemName: undefined, status: 'UNMATCHED' });
  async function rematch() { const d = await api.post('/import/invoice/match', { lines: lines!.map(l => ({ rawName: l.rawName, quantity: l.quantity === '' ? null : Number(l.quantity) })) }); setLines(l => l!.map((x, i) => (x.itemId && x.status === 'MATCHED' ? x : { ...x, ...mk([d.rows[i]])[0], key: x.key, quantity: x.quantity }))); }
  const ready = (lines || []).filter(l => l.itemId && Number(l.quantity) > 0); const skipped = (lines?.length || 0) - ready.length;
  async function confirmIt() {
    if (!supplierId) return setErr('Choose the supplier for this invoice'); if (!ready.length) return setErr('No matched lines with a quantity');
    if (!confirm(`Add ${ready.length} purchase line(s) and increase stock?${skipped ? `\n\n${skipped} unmatched or empty line(s) will be ignored.` : ''}`)) return;
    setBusy(true); setErr(''); try { const d = await api.post('/purchases/bulk', { date, supplierId, invoiceNumber: invNo || undefined, invoiceId: invoiceId || undefined, lines: ready.map(l => ({ itemId: l.itemId, quantity: Number(l.quantity) })) }); setDone(d); toast('Purchases recorded'); } catch (e: any) { setErr(e.message); } finally { setBusy(false); }
  }
  if (done) return <div className="card p-6 max-w-xl space-y-3"><h2 className="text-lg font-semibold text-ok">{done.created} purchase line(s) recorded</h2><p className="text-sm">Stock has been increased and each line is in the audit trail.</p><div className="flex gap-2"><Link className="btn btn-primary" to="/purchases">View purchases</Link><button className="btn" onClick={() => { setDone(null); setLines(null); setFile(null); setInvoiceId(''); }}>Read another invoice</button></div></div>;
  if (!lines) return <div className="card p-5 max-w-2xl space-y-3"><h2 className="font-semibold">Read a supplier invoice</h2><p className="text-sm text-slate-600">Upload a photo or PDF. We read only the item names and quantities, then you review them before any stock changes.</p><ErrorBox msg={err} />
    <input className="inp" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e => setFile(e.target.files?.[0] || null)} /><button className="btn btn-primary" disabled={!file || busy} onClick={extract}>{busy ? 'Reading invoice…' : 'Read invoice'}</button></div>;
  const badge = (s: string) => s === 'MATCHED' ? <span className="rounded bg-ok px-2 py-0.5 text-xs font-semibold text-white">Matched</span> : s === 'SUGGESTED' ? <span className="rounded bg-warn px-2 py-0.5 text-xs font-semibold">Check match</span> : <span className="rounded bg-bad px-2 py-0.5 text-xs font-semibold text-white">Unmatched</span>;
  return <div className="space-y-4"><div className="card p-4 space-y-3"><div className="flex justify-between items-center"><h2 className="font-semibold">Review extracted items — stock has not changed yet</h2><div className="flex gap-2">{invoiceId && <button className="btn" onClick={() => download('/import/invoice/' + invoiceId + '/file', 'invoice', true)}>View invoice</button>}<button className="btn" onClick={() => { setLines(null); setFile(null); }}>Start over</button></div></div>
    <ErrorBox msg={err || ocrErr} />{ocrErr && <p className="text-sm text-slate-600">You can add the lines by hand below.</p>}
    <div className="grid gap-3 sm:grid-cols-3"><Field label="Supplier"><SupplierSelect value={supplierId} onChange={setSup} includeAll="Choose supplier…" /></Field><Field label="Invoice date"><input className="inp" type="date" value={date} max={today()} onChange={e => setDate(e.target.value)} /></Field><Field label="Invoice number (optional)"><input className="inp" value={invNo} onChange={e => setInvNo(e.target.value)} /></Field></div></div>
    <div className="card overflow-hidden"><div className="overflow-x-auto"><table className="tbl"><thead><tr><th>Item name (as read)</th><th className="w-28">Quantity</th><th>Match status</th><th>Item in your master list</th><th></th></tr></thead>
      <tbody>{lines.map(l => <tr key={l.key}><td><input className="inp" value={l.rawName} onChange={e => upd(l.key, { rawName: e.target.value })} aria-label="Item name" /></td><td><input className="inp" type="number" min={0} step="any" value={l.quantity} onChange={e => upd(l.key, { quantity: e.target.value })} aria-label="Quantity" /></td><td>{badge(l.status)}</td>
        <td className="min-w-[16rem]">{l.itemId ? <ItemPicker value={{ id: l.itemId, name: l.itemName! }} onPick={i => link(l.key, i)} /> : <div className="space-y-1">{l.candidates.length > 0 && <div className="flex flex-wrap gap-1">{l.candidates.map((c: any) => <button key={c.id} className="btn !py-0.5 text-xs" onClick={() => link(l.key, { id: c.id, name: c.name })}>{c.name}</button>)}</div>}<ItemPicker value={null} onPick={i => link(l.key, i)} placeholder="Search item to link…" /></div>}</td>
        <td><button className="text-bad text-xs underline" onClick={() => setLines(x => x!.filter(y => y.key !== l.key))}>Remove</button></td></tr>)}</tbody></table></div>
      <div className="flex flex-wrap gap-2 p-3 border-t border-slate-100"><button className="btn" onClick={() => setLines(l => [...l!, { key: Date.now(), rawName: '', quantity: '', status: 'UNMATCHED', candidates: [] }])}>Add line</button><button className="btn" onClick={rematch}>Re-check matches</button></div></div>
    <div className="card p-4 flex flex-wrap items-center justify-between gap-3"><div className="text-sm"><b>{ready.length}</b> line(s) ready · <b className={skipped ? 'text-bad' : ''}>{skipped}</b> will be ignored (unmatched or no quantity)</div><button className="btn btn-primary" disabled={busy || !ready.length} onClick={confirmIt}>Confirm and add to stock</button></div></div>;
}

// ---------------------------------------------------------------- History
function History() {
  const toast = useToast(); const [page, setPage] = useState(1); const { data, loading, error, reload } = useApi('/import/logs?page=' + page);
  const rb = async (id: string) => { if (!confirm('Undo this import? Items it created are removed (if untouched since) and stock/criteria it changed are restored.')) return; try { const r = await api.post(`/import/logs/${id}/rollback`); toast(`Rolled back: ${r.removed} removed, ${r.restored} restored`); reload(); } catch (e: any) { toast(e.message, 'err'); } };
  return <div className="card overflow-hidden"><ErrorBox msg={error} />{loading && !data ? <Spinner /> : !data?.rows.length ? <Empty>No imports yet.</Empty> : <div className="overflow-x-auto"><table className="tbl"><thead><tr><th>When</th><th>Type</th><th>File</th><th>By</th><th className="text-right">Rows</th><th className="text-right">Created</th><th className="text-right">Updated</th><th className="text-right">Failed</th><th>Status</th><th></th></tr></thead>
    <tbody>{data.rows.map((l: any) => <tr key={l._id}><td className="whitespace-nowrap">{fmtDate(l.appliedAt || l.createdAt)}</td><td>{l.kind === 'MASTER' ? 'Master data' : 'Stock quantity'}</td><td>{l.fileName}</td><td>{l.userName}</td><td className="text-right">{l.counts?.total ?? '—'}</td><td className="text-right">{l.counts?.created ?? '—'}</td><td className="text-right">{l.counts?.updated ?? '—'}</td><td className="text-right">{l.counts?.failed ?? '—'}</td><td>{l.status === 'APPLIED' ? 'Applied' : l.status === 'ROLLED_BACK' ? 'Rolled back' : l.status}</td><td>{l.status === 'APPLIED' && <button className="btn !py-1" onClick={() => rb(l._id)}>Undo</button>}</td></tr>)}</tbody></table></div>}
    {data && <Pager page={data.page} pages={data.pages} total={data.total} onPage={setPage} />}</div>;
}
