import { useState } from 'react';
import { api, download, qs } from '../api';
import { DateFilters, dateParams, Empty, ErrorBox, Field, fmtDate, fmtNum, ItemPicker, Modal, PageHeader, Pager, Spinner, SupplierSelect, today, useApi, useToast } from '../ui';

const addDays = (n: number) => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata' }).format(new Date(Date.now() + n * 864e5));
/** Orders given to suppliers: what, how much, expected date. Sales team sees pending qty + date on their screen. */
export default function Orders() {
  const toast = useToast(); const [status, setStatus] = useState('OPEN'); const [supplierId, setS] = useState(''); const [d, setD] = useState({ preset: '', from: '', to: '' }); const [page, setPage] = useState(1); const [create, setCreate] = useState(false); const [edit, setEdit] = useState<any>(null);
  const f = { status, supplierId, ...dateParams(d) }; const { data, loading, error, reload } = useApi('/orders' + qs({ ...f, page, limit: 50 }));
  const cancel = async (l: any) => { if (!confirm(`Cancel the pending order of ${l.itemId?.name}?`)) return; try { await api.put('/orders/lines/' + l._id, { cancel: true }); toast('Order line cancelled'); reload(); } catch (e: any) { toast(e.message, 'err'); } };
  return <><PageHeader title="Supplier orders" sub="What you ordered, from whom, how much, and by when it should arrive"><button className="btn" onClick={() => download('/reports/orders' + qs({ ...f, format: 'xlsx' }))}>Export Excel</button><button className="btn btn-primary" onClick={() => setCreate(true)}>New order</button></PageHeader>
    <div className="card p-3 mb-3 flex flex-wrap gap-2 items-center"><select className="inp !w-auto" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="OPEN">Pending</option><option value="RECEIVED">Received</option><option value="CANCELLED">Cancelled</option><option value="all">All</option></select><SupplierSelect className="inp !w-auto" value={supplierId} onChange={v => { setS(v); setPage(1); }} includeAll="All suppliers" /><DateFilters v={d} set={(x: any) => { setD(x); setPage(1); }} /></div>
    <ErrorBox msg={error} /><div className="card overflow-hidden">{loading && !data ? <Spinner /> : !data?.rows.length ? <Empty>No orders found. Use “Order now” on the Reorder page to create one in a click.</Empty> : <div className="overflow-x-auto"><table className="tbl"><thead><tr><th>Order no.</th><th>Date</th><th>Supplier</th><th>Item</th><th className="text-right">Ordered</th><th className="text-right">Received</th><th className="text-right">Pending</th><th>Expected by</th><th></th></tr></thead>
      <tbody>{data.rows.map((l: any) => <tr key={l._id}><td className="whitespace-nowrap">{l.orderNo}</td><td className="whitespace-nowrap">{fmtDate(l.orderDate)}</td><td>{l.supplierId?.name}</td><td className="font-medium">{l.itemId?.name}</td><td className="text-right tabular-nums">{fmtNum(l.quantity)}</td><td className="text-right tabular-nums">{fmtNum(l.receivedQty)}</td><td className="text-right tabular-nums font-semibold">{l.status === 'OPEN' ? fmtNum(l.quantity - l.receivedQty) : '—'}</td><td className="whitespace-nowrap">{fmtDate(l.expectedDate)}</td>
        <td className="whitespace-nowrap">{l.status === 'OPEN' ? <><button className="btn !py-1 mr-1" onClick={() => setEdit(l)}>Change date</button><button className="text-bad text-xs underline" onClick={() => cancel(l)}>Cancel</button></> : <span className="text-xs text-slate-500">{l.status === 'RECEIVED' ? 'Received' : 'Cancelled'}</span>}</td></tr>)}</tbody></table></div>}
      {data && <Pager page={data.page} pages={data.pages} total={data.total} onPage={setPage} />}</div>
    {create && <NewOrder onClose={() => setCreate(false)} onSaved={() => { setCreate(false); reload(); }} />}
    {edit && <Modal title={`Expected date: ${edit.itemId?.name}`} onClose={() => setEdit(null)}><EditDate l={edit} onSaved={() => { setEdit(null); reload(); }} /></Modal>}</>;
}
function EditDate({ l, onSaved }: { l: any; onSaved: () => void }) {
  const [d, setD] = useState((l.expectedDate || '').slice(0, 10) || addDays(7)); const [err, setErr] = useState('');
  return <div className="space-y-3"><ErrorBox msg={err} /><Field label="Expected by"><input className="inp" type="date" value={d} onChange={e => setD(e.target.value)} /></Field><button className="btn btn-primary" onClick={async () => { try { await api.put('/orders/lines/' + l._id, { expectedDate: d }); onSaved(); } catch (e: any) { setErr(e.message); } }}>Save</button></div>;
}
function NewOrder({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const toast = useToast(); const [supplierId, setSup] = useState(''); const [exp, setExp] = useState(addDays(7)); const [lines, setLines] = useState<{ key: number; item: any; qty: string }[]>([{ key: 1, item: null, qty: '' }]); const [err, setErr] = useState('');
  const set = (k: number, p: any) => setLines(l => l.map(x => (x.key === k ? { ...x, ...p } : x)));
  async function save() { const ok = lines.filter(l => l.item && Number(l.qty) > 0); if (!supplierId) return setErr('Choose a supplier'); if (!ok.length) return setErr('Add at least one item and quantity');
    try { const r = await api.post('/orders', { supplierId, expectedDate: exp, lines: ok.map(l => ({ itemId: l.item.id, quantity: Number(l.qty) })) }); toast(`Order ${r.orderNo} created`); onSaved(); } catch (e: any) { setErr(e.message); } }
  return <Modal title="New supplier order" onClose={onClose} wide><div className="space-y-3"><ErrorBox msg={err} /><div className="grid gap-3 sm:grid-cols-2"><Field label="Supplier"><SupplierSelect value={supplierId} onChange={setSup} includeAll="Choose supplier…" /></Field><Field label="Expected by"><input className="inp" type="date" min={today()} value={exp} onChange={e => setExp(e.target.value)} /></Field></div>
    {lines.map(l => <div key={l.key} className="grid grid-cols-[1fr_6.5rem_auto] gap-2 items-start"><ItemPicker value={l.item} onPick={i => set(l.key, { item: i })} /><input className="inp" type="number" min={0} placeholder="Qty" value={l.qty} onChange={e => set(l.key, { qty: e.target.value })} /><button className="text-bad text-sm underline pt-2" onClick={() => setLines(x => (x.length > 1 ? x.filter(y => y.key !== l.key) : x))}>Remove</button></div>)}
    <div className="flex gap-2"><button className="btn" onClick={() => setLines(l => [...l, { key: Date.now(), item: null, qty: '' }])}>Add line</button><button className="btn btn-primary" onClick={save}>Place order</button></div></div></Modal>;
}
